# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Work in progress
email: belyaev@kspt.icc.spbstu.ru
description: >- # this means to ignore newlines until "baseurl:"
  Your description will be here, too
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
name: "Mikhail Belyaev"
twitter_username: koppcapp
github_username: belyaev-mikhail
minimal_mistakes_skin: dark
search: true

twitter:
  username: koppcapp

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.16.5"
plugins:
  - jekyll-feed
  - jekyll-include-cache

include:
  - _pages

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
author_profile: true

comments:
  provider: disqus
  disqus:
    shortname: "belyaev-mikhail-github-io"
